name:             markdown-unlit
version:          0.5.1
synopsis:         Literate Haskell support for Markdown
category:         Development
license:          MIT
copyright:        (c) 2012-2021 Simon Hengel
author:           Simon Hengel <sol@typeful.net>
maintainer:       Simon Hengel <sol@typeful.net>
description:      "Documentation is here: <https://github.com/sol/markdown-unlit#readme>"

github: sol/markdown-unlit

ghc-options: -Wall

dependencies:
  - base == 4.*
  - base-compat

library:
  source-dirs: src

executables:
  markdown-unlit:
    main: Main.hs
    source-dirs:
      - driver
    dependencies:
      - markdown-unlit

tests:
  spec:
    defaults: hspec/defaults@v0.1.0
    cpp-options: -DTEST
    source-dirs:
      - src
    dependencies:
      - directory
      - QuickCheck
      - silently
      - stringbuilder
      - temporary
