name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        ghc:
          - '8.6'
          - '8.8'
          - '8.10'
        include:
          - os: macos-latest
            ghc: latest
          - os: windows-latest
            ghc: latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: sol/run-haskell-tests@v1

  success:
    needs: [build]
    runs-on: ubuntu-latest
    steps: [run: echo success]
