name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        ghc:
          - '8.6'
          - '8.8'
          - '8.10'
        include:
          - os: macos-latest
            ghc: latest
          - os: windows-latest
            ghc: latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - run: cabal update
      - run: cabal configure --enable-tests --enable-benchmarks # NOTE: --enable-tests is necessary due to https://github.com/haskell/cabal/issues/5079
      - run: cabal build all
      - run: cabal test all --test-show-details=direct
        env:
          HSPEC_OPTIONS: --color

  success:
    needs: [build]
    runs-on: ubuntu-latest
    steps: [run: echo success]
